name: cmos-dump
summary: CMOS dumping tool
description: This tool dumps the CMOS data in a human readable form
confinement: strict
grade: stable
type: app
assumes: [snapd2.45]
base: core18
adopt-info: cmos-dump

architectures:
    - amd64
    - i386

parts:
    cmos-dump:
        plugin: make
        source: https://github.com/ColinIanKing/cmos-dump.git
        override-pull: |
            snapcraftctl pull
            description="$(git describe HEAD --tags)"
            sha=$(echo $description | tr '-' ' ' | awk '{print $NF}')
            version=${description%$sha}
            commits=$(git log --oneline | wc -l)
            date=$(date +'%Y%m%d')
            if test "$description" = "$sha"
            then
                version="$description"
            else
                version=$(echo $version$date-$commits-$sha | cut -c1-32)
            fi
            snapcraftctl set-version "$version"

        build-packages:
            - gcc
            - make

apps:
    cmos-dump:
        command: usr/sbin/cmos-dump
        plugs:
            - io-ports-control
